modLoader="lowcodefml"
showAsResourcePack = false
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="hero"
version="1.0.0"
logoFile = "logo.png"
logoBlur = false
displayName="heros"
description='''
hero addon
'''

[[dependencies.hero]]
modId = "palladium"
mandatory = true
versionRange = "[4.4.2,)"
ordering = "NONE"
side = "BOTH"
